SELECT CODE, NAME, PRICE FROM MENU;
SELECT NO, NAME FROM TABLEINFO;
SELECT NO, CODE, ORDERDAY, CNT, ISPAYMENT FROM MENU_ORDER;


SELECT  *
FROM MENU_ORDER o JOIN MENU m ON o.CODE = m.CODE JOIN TABLEINFO t ON o.NO = t.NO;